spring:
  application:
    name: eureka-service
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    ip-address: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      desfauleZone: ${eureka.instance.hostname}:${server.port}/eureka
