

server:
  port: 9991
spring:
  application:
    name: user-service

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 10
    ip-address: localhost
    prefer-ip-address: true
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://182.92.77.133:8761/eureka
