
server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          #            - Header=Cookie,Set-Cookie
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 10
    ip-address: localhost
    prefer-ip-address: true
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://182.92.77.133:8761/eureka

